/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestortareas.IGU;

import com.mycompany.gestortareas.LOGIC.Usuario;
import com.mycompany.gestortareas.PERSISTENSE.ITareaDAO;
import com.mycompany.gestortareas.PERSISTENSE.IUsuarioDAO;
import com.mycompany.gestortareas.PERSISTENSE.TareaDaoImplementSql;
import com.mycompany.gestortareas.PERSISTENSE.UsuarioDaoImplementSql;

/**
 *
 * @author kenrr
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }
    public void cargarTareasUsuario(int id) {
        usuario.setTareas(daot.listarTarea(id));
        panelCargar.setVisible(true);
        iniciarTarea();
        
    }
    public void iniciarTarea(){
        Tdescripcion.setText(usuario.getTareas().get(contador).getDescripcion());
        Testado.setText(String.valueOf(usuario.getTareas().get(contador).getEstado()));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tcontraseña = new javax.swing.JTextField();
        Tconfirmacion = new javax.swing.JTextField();
        Bcargar = new javax.swing.JButton();
        BverTareas = new javax.swing.JButton();
        BcrearTarea = new javax.swing.JButton();
        panelTarjeta = new javax.swing.JPanel();
        panelCargar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdescripcion = new javax.swing.JTextArea();
        Testado = new javax.swing.JTextField();
        BotonTareaAnterior = new javax.swing.JButton();
        BotonTareaSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Nombre");

        jLabel2.setText("Contraseña");

        Bcargar.setText("Cargar");
        Bcargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BcargarMousePressed(evt);
            }
        });

        BverTareas.setText("Ver");

        BcrearTarea.setText("Crear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Tconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(BverTareas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Tcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(Bcargar)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BcrearTarea)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Tcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bcargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tconfirmacion)
                    .addComponent(BverTareas)
                    .addComponent(BcrearTarea))
                .addGap(360, 360, 360))
        );

        panelTarjeta.setBackground(new java.awt.Color(51, 51, 255));
        panelTarjeta.setLayout(new java.awt.CardLayout());

        panelCargar.setBackground(new java.awt.Color(204, 255, 204));

        Tdescripcion.setColumns(20);
        Tdescripcion.setRows(5);
        jScrollPane1.setViewportView(Tdescripcion);

        Testado.setText("jTextField1");

        BotonTareaAnterior.setText("<<");
        BotonTareaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonTareaAnteriorMousePressed(evt);
            }
        });

        BotonTareaSiguiente.setText(">>");
        BotonTareaSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonTareaSiguienteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelCargarLayout = new javax.swing.GroupLayout(panelCargar);
        panelCargar.setLayout(panelCargarLayout);
        panelCargarLayout.setHorizontalGroup(
            panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarLayout.createSequentialGroup()
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonTareaAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonTareaSiguiente)
                    .addComponent(Testado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCargarLayout.setVerticalGroup(
            panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Testado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonTareaAnterior)
                    .addComponent(BotonTareaSiguiente))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        panelTarjeta.add(panelCargar, "card2");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(panelTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcargarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcargarMousePressed
        if(Tcontraseña.getText() != ""&& Tnombre.getText() != ""){
            usuario = dao.leerUsuario(Tnombre.getText(), Tcontraseña.getText());
            if (usuario!=null) {
                Tconfirmacion.setText(String.valueOf(usuario.getId()));
                cargarTareasUsuario(usuario.getId());
                panelCargar.setVisible(false);
            }
        }
    }//GEN-LAST:event_BcargarMousePressed

    private void BotonTareaAnteriorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTareaAnteriorMousePressed
        if (contador>0) {
            contador--;
            iniciarTarea();
        }
    }//GEN-LAST:event_BotonTareaAnteriorMousePressed

    private void BotonTareaSiguienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTareaSiguienteMousePressed
        if (contador<usuario.getTareas().size()-1) {
            contador++;
            iniciarTarea();
        }
        
    }//GEN-LAST:event_BotonTareaSiguienteMousePressed

    /**
     * @param args the command line arguments
     */
    
    // Variables porpias
    private Usuario usuario = null;
    private IUsuarioDAO  dao = new UsuarioDaoImplementSql();
    private ITareaDAO daot = new TareaDaoImplementSql();
    private int contador = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcargar;
    private javax.swing.JButton BcrearTarea;
    private javax.swing.JButton BotonTareaAnterior;
    private javax.swing.JButton BotonTareaSiguiente;
    private javax.swing.JButton BverTareas;
    private javax.swing.JTextField Tconfirmacion;
    private javax.swing.JTextField Tcontraseña;
    private javax.swing.JTextArea Tdescripcion;
    private javax.swing.JTextField Testado;
    private javax.swing.JTextField Tnombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCargar;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTarjeta;
    // End of variables declaration//GEN-END:variables
}
