/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestortareas.IGU;

import com.mycompany.gestortareas.LOGIC.Usuario;
import com.mycompany.gestortareas.PERSISTENSE.ITareaDAO;
import com.mycompany.gestortareas.PERSISTENSE.IUsuarioDAO;
import com.mycompany.gestortareas.PERSISTENSE.TareaDaoImplementSql;
import com.mycompany.gestortareas.PERSISTENSE.UsuarioDaoImplementSql;
import javax.swing.JOptionPane;

/**
 *
 * @author kenrr
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        panelCargar.setVisible(false);
        panelCrear.setVisible(false);
        panelVacio.setVisible(true);
    }
    public void cargarTareasUsuario(int id) {
        usuario.setTareas(daot.listarTarea(id));
        panelCargar.setVisible(true);
        iniciarTarea();
        
    }
    public void iniciarTarea(){
        Tdescripcion.setText(usuario.getTareas().get(contador).getDescripcion());
        Testado.setText(String.valueOf(usuario.getTareas().get(contador).getEstado()));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tcontraseña = new javax.swing.JTextField();
        Tconfirmacion = new javax.swing.JTextField();
        Bcargar = new javax.swing.JButton();
        BverTareas = new javax.swing.JButton();
        BcrearTarea = new javax.swing.JButton();
        panelTarjeta = new javax.swing.JPanel();
        panelCrear = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TcrearTarea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Bcrear = new javax.swing.JButton();
        panelCargar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdescripcion = new javax.swing.JTextArea();
        Testado = new javax.swing.JTextField();
        BotonTareaAnterior = new javax.swing.JButton();
        BotonTareaSiguiente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelVacio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setText("Nombre");

        jLabel2.setText("Contraseña");

        Bcargar.setText("Cargar");
        Bcargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BcargarMousePressed(evt);
            }
        });

        BverTareas.setText("Ver");
        BverTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BverTareasMousePressed(evt);
            }
        });

        BcrearTarea.setText("Crear");
        BcrearTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BcrearTareaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Tconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(BverTareas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Tcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bcargar)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BcrearTarea)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Tcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bcargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tconfirmacion)
                    .addComponent(BverTareas)
                    .addComponent(BcrearTarea))
                .addGap(360, 360, 360))
        );

        panelTarjeta.setBackground(new java.awt.Color(51, 51, 255));
        panelTarjeta.setLayout(new java.awt.CardLayout());

        panelCrear.setBackground(new java.awt.Color(255, 51, 51));

        TcrearTarea.setColumns(20);
        TcrearTarea.setRows(5);
        jScrollPane2.setViewportView(TcrearTarea);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Crear nueva tarea");

        Bcrear.setText("Crear");
        Bcrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BcrearMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bcrear)
                    .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bcrear)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        panelTarjeta.add(panelCrear, "card3");

        panelCargar.setBackground(new java.awt.Color(204, 255, 204));

        Tdescripcion.setColumns(20);
        Tdescripcion.setRows(5);
        jScrollPane1.setViewportView(Tdescripcion);

        Testado.setText("jTextField1");

        BotonTareaAnterior.setText("<<");
        BotonTareaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonTareaAnteriorMousePressed(evt);
            }
        });

        BotonTareaSiguiente.setText(">>");
        BotonTareaSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonTareaSiguienteMousePressed(evt);
            }
        });

        jButton1.setText("Cambiar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelCargarLayout = new javax.swing.GroupLayout(panelCargar);
        panelCargar.setLayout(panelCargarLayout);
        panelCargarLayout.setHorizontalGroup(
            panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarLayout.createSequentialGroup()
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCargarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(panelCargarLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BotonTareaAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonTareaSiguiente)
                    .addComponent(Testado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        panelCargarLayout.setVerticalGroup(
            panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarLayout.createSequentialGroup()
                        .addComponent(Testado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonTareaAnterior)
                    .addComponent(BotonTareaSiguiente))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        panelTarjeta.add(panelCargar, "card2");

        panelVacio.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        panelTarjeta.add(panelVacio, "card4");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcargarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcargarMousePressed
        if(Tcontraseña.getText() != ""&& Tnombre.getText() != ""){
            usuario = dao.leerUsuario(Tnombre.getText(), Tcontraseña.getText());
            if (usuario!=null) {
                Tconfirmacion.setText(String.valueOf(usuario.getId()));
                cargarTareasUsuario(usuario.getId());
                panelCargar.setVisible(true);
                panelCrear.setVisible(false);
            }
        }
    }//GEN-LAST:event_BcargarMousePressed

    private void BotonTareaAnteriorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTareaAnteriorMousePressed
        if (contador>0) {
            contador--;
            iniciarTarea();
        }
    }//GEN-LAST:event_BotonTareaAnteriorMousePressed

    private void BotonTareaSiguienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTareaSiguienteMousePressed
        if (contador<usuario.getTareas().size()-1) {
            contador++;
            iniciarTarea();
        }
        
    }//GEN-LAST:event_BotonTareaSiguienteMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        daot.actualizarTarea(usuario.getTareas().get(contador).getId());
        usuario.getTareas().get(contador).setEstado(!usuario.getTareas().get(contador).getEstado());
        iniciarTarea();
    }//GEN-LAST:event_jButton1MousePressed

    private void BcrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcrearMousePressed
        if (TcrearTarea.getText()!="") {
            daot.crearTarea(usuario.getId(), TcrearTarea.getText());
            JOptionPane.showMessageDialog(null, "Agregado");
        }
    }//GEN-LAST:event_BcrearMousePressed

    private void BverTareasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BverTareasMousePressed
        if (usuario!=null) {
            panelCargar.setVisible(true);
        panelCrear.setVisible(false);
        cargarTareasUsuario(usuario.getId());
        }
    }//GEN-LAST:event_BverTareasMousePressed

    private void BcrearTareaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcrearTareaMousePressed
        if (usuario!=null) {
            panelCargar.setVisible(false);
            panelCrear.setVisible(true);
        }
    }//GEN-LAST:event_BcrearTareaMousePressed

    /**
     * @param args the command line arguments
     */
    
    // Variables porpias
    private Usuario usuario = null;
    private IUsuarioDAO  dao = new UsuarioDaoImplementSql();
    private ITareaDAO daot = new TareaDaoImplementSql();
    private int contador = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcargar;
    private javax.swing.JButton Bcrear;
    private javax.swing.JButton BcrearTarea;
    private javax.swing.JButton BotonTareaAnterior;
    private javax.swing.JButton BotonTareaSiguiente;
    private javax.swing.JButton BverTareas;
    private javax.swing.JTextField Tconfirmacion;
    private javax.swing.JTextField Tcontraseña;
    private javax.swing.JTextArea TcrearTarea;
    private javax.swing.JTextArea Tdescripcion;
    private javax.swing.JTextField Testado;
    private javax.swing.JTextField Tnombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelCargar;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTarjeta;
    private javax.swing.JPanel panelVacio;
    // End of variables declaration//GEN-END:variables
}
